### ISSUE TITLE
Navbar buttons are no longer displayed

### ISSUE THREAD

**Issue by Oli0li** [Contributees/First-Ruby-Quest#19]
I noticed today that the "Dashboard"/"Log in"/"Log out"/"Sign up" buttons that were previously displayed on the navbar are no longer visible. It would be good to look into why they are no longer displayed and fix this.

**Comment by Oli0li** [comment]
I just took a peek while looking into the app, I think it's probably because some of the Bootstrap classes we were using are no longer working here. I have an idea for a very simple Tailwind version, but I'm by no means a Tailwind expert. Is that OK @awalsh3 if I open a PR for this and you review it if/when you have time? I'm happy to review your version if you already started on this! 😊

**Comment by ClaireDMT** [comment]
@Oli0li I am gonna use the tailwind component to do a quick revamp of the navbar this afternoon. I found a cosy café!

**Comment by awalsh3** [comment]
Perfect, all looks good to me! Thanks for picking up the task Claire!
